// ============================================================
// Prospera – Shared Mock Data Store
// ============================================================
const ProspecraData = {
  kpis: {
    revenue:    { value: '$124,500', trend: '+12.5%', up: true,  label: 'Total Revenue',   icon: 'payments' },
    users:      { value: '8,432',    trend: '+4.2%',  up: true,  label: 'Active Users',    icon: 'group' },
    conversion: { value: '3.8%',     trend: '-1.1%',  up: false, label: 'Avg. Conversion', icon: 'donut_large' },
    health:     { value: '99.9%',    trend: 'Optimal',up: true,  label: 'System Health',   icon: 'monitor_heart' }
  },
  activity: [
    { icon: 'file_download', color: 'primary',  title: 'Q3 Report Exported',    sub: 'Generated by System Admin',       time: '10 mins ago' },
    { icon: 'check_circle',  color: 'success',  title: 'Database Synced',        sub: 'All clusters synchronized',       time: '2 hours ago' },
    { icon: 'warning',       color: 'warning',  title: 'API Rate Limit Nearing', sub: 'Service: Payment Gateway',        time: '5 hours ago' },
    { icon: 'person_add',    color: 'tertiary', title: 'New User Role Added',    sub: "'Analyst' role created by Admin", time: '1 day ago' }
  ],
  inventory: [
    { name:'Quantum Processor Core X9',  cat:'Computing Components', stock:42,   stockTrend:'-15%', status:'Critical', depletion:'Oct 24, 2023', daysLeft:'3 Days' },
    { name:'Industrial Sensor Array M2', cat:'IoT Devices',          stock:185,  stockTrend:'',     status:'Low Stock',depletion:'Nov 02, 2023', daysLeft:'12 Days' },
    { name:'Standard Logic Controller',  cat:'Control Units',         stock:1402, stockTrend:'+5%',  status:'Healthy',  depletion:'Jan 15, 2024', daysLeft:'' },
    { name:'Thermal Management Module',  cat:'Cooling Systems',       stock:850,  stockTrend:'',     status:'Healthy',  depletion:'Dec 05, 2023', daysLeft:'' },
    { name:'Fiber Optic Hub Pro',        cat:'Networking',            stock:290,  stockTrend:'+2%',  status:'Healthy',  depletion:'Feb 01, 2024', daysLeft:'' },
    { name:'Voltage Regulator VR-400',   cat:'Power Systems',         stock:60,   stockTrend:'-8%',  status:'Low Stock',depletion:'Oct 30, 2023', daysLeft:'9 Days' }
  ],
  reports: [
    { icon:'inventory_2',          title:'Q3 Inventory Audit',     desc:'Comprehensive analysis of warehouse stock levels across NA region.',    date:'Today, 09:41 AM', status:'ready',      progress:100 },
    { icon:'monitoring',           title:'Monthly Sales Velocity', desc:'Product performance breakdown by SKU and channel.',                     date:'Yesterday',       status:'ready',      progress:100 },
    { icon:'group',                title:'Customer Churn Risk',    desc:'Predictive model output for at-risk enterprise accounts.',              date:'Generating... 84%',status:'processing', progress:84  },
    { icon:'account_balance_wallet',title:'OpEx Summary',          desc:'Departmental breakdown of operational expenses vs budget.',             date:'Oct 12',          status:'ready',      progress:100 }
  ],
  customers: [
    { initials:'JD', name:'Jane Doe',     email:'jane.doe@enterprise.co', status:'ACTIVE',   ltv:'$12,450', last:'2 days ago',   cohort:'Champions' },
    { initials:'AS', name:'Alex Smith',   email:'alex.s@techcorp.io',     status:'ACTIVE',   ltv:'$9,210',  last:'5 days ago',   cohort:'Champions' },
    { initials:'RJ', name:'Rachel Jones', email:'rjones@global.net',      status:'ACTIVE',   ltv:'$8,750',  last:'1 week ago',   cohort:'Champions' },
    { initials:'MB', name:'Mike Brown',   email:'mbrown@corp.com',        status:'INACTIVE', ltv:'$3,200',  last:'2 months ago', cohort:'At Risk'   },
    { initials:'SL', name:'Sara Lee',     email:'sara.l@b2b.org',         status:'ACTIVE',   ltv:'$6,100',  last:'3 days ago',   cohort:'Loyalists' }
  ],
  forecasting: {
    projectedRevenue: '$2.4M',
    forecastAccuracy: '94.2%',
    atRiskOpportunities: 14
  }
};
